apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: patch-and-transform #--Name of your choice
spec:
  package: ghcr.io/crossplane-contrib/function-patch-and-transform:v0.9.0 #--https://github.com/orgs/crossplane-contrib/packages