apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: somephone
  namespace: client-certificates
spec:
  isCA: false
  duration: 26280h #--1 year. Really this is too long but practical, as
  subject:         #--we have no innate means of rotating certificates.
    organizations:
      - tinfoilcipher
    organizationalUnits:
      - Ops
    countries:
      - GB
  dnsNames:
    - somephone.tinfoilcipher.co.uk
  secretName: somephone
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: somelaptop
  namespace: client-certificates
spec:
  isCA: false
  duration: 8760h
  subject:
    organizations:
      - tinfoilcipher
    organizationalUnits:
      - Ops
    countries:
      - GB
  dnsNames:
    - somelaptop.tinfoilcipher.co.uk
  secretName: somelaptop-certificate
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
