#--freeradius.yaml

kind: Deployment
apiVersion: apps/v1
metadata:
  name: freeradius
  namespace: freeradius
spec:
  replicas: 2
  selector:
    matchLabels:
      name: freeradius
  template:
    metadata:
      name: freeradius
      labels:
        name: freeradius
    spec:
      volumes:
      - name: raddb-files
        configMap:
          name: freeradius-files
          optional: true
      - name: raddb-secrets
        secret:
          defaultMode: 420
          secretName: freeradius-secrets
      - name: radius-server-certificate
        secret:
          defaultMode: 420
          secretName: freeradius-server-certificate
      containers:
        - name: freeradius
          image: 'freeradius/freeradius-server:latest-alpine'
          ports:
            - containerPort: 1812
              protocol: UDP
            - containerPort: 1813
              protocol: UDP
          volumeMounts:
            - name: raddb-secrets
              mountPath: /etc/raddb/mods-config/files/authorize
              subPath: authorize
              readOnly: true
            - name: raddb-secrets
              mountPath: /etc/raddb/clients.conf
              subPath: clients.conf
              readOnly: true
            - name: raddb-files
              mountPath: /etc/raddb/radiusd.conf
              subPath: radiusd.conf
              readOnly: true
            - mountPath: /etc/raddb/mods-enabled/eap
              name: raddb-files
              readOnly: true
              subPath: eap
            - mountPath: /etc/ssl/certs/ca.crt
              name: radius-server-certificate
              readOnly: true
              subPath: ca.crt
            - mountPath: /etc/ssl/certs/tls.crt
              name: radius-server-certificate
              readOnly: true
              subPath: tls.crt
            - mountPath: /etc/ssl/private/tls.key
              name: radius-server-certificate
              readOnly: true
              subPath: tls.key
---
kind: Service
apiVersion: v1
metadata:
  name: lb-freeradius
  namespace: radius
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  ports:
    - name: 'radius'
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: 'radius-acct'
      protocol: UDP
      port: 1813
      targetPort: 1813
  selector:
    name: freeradius
  type: LoadBalancer
  loadBalancerIP: 10.0.0.199 #--Set as appropriate for your loadbalancer