#--Create an application certificate for RADIUS services
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: freeradius
  namespace: freeradius
spec:
  isCA: false
  subject:
    organizations:
      - tinfoilcipher
    organizationalUnits:
      - Ops
    countries:
      - GB
  dnsNames:
    - freeradius.freeradius.svc.cluster.local
    - freeradius.tinfoilcipher.co.uk
  secretName: freeradius-server-certificate
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
