#--client.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: someclient
  namespace: client-certificates
spec:
  isCA: false #--Specifies not a CA cert
  duration: 2160h #--90 days
  subject:
    organizations:
      - tinfoilcipher
    organizationalUnits:
      - Ops
    countries:
      - GB
  dnsNames:
    - someclient.tinfoilcipher.co.uk
  secretName: someclient
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer          #--Issuer
    kind: ClusterIssuer      #--details
    group: cert-manager.io
